// Copy the built SDK (dist/) into every destination listed in sdk.deploy.json.
//
// This is the "deployment" mechanism: rather than a git submodule, the compiled
// SDK is vendored into each consuming project so it builds with the consumer's
// own toolchain. Each target folder is wiped and replaced so removed files do
// not linger. Run directly (`node scripts/deploy.js`) or imported by watch.js.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CONFIG = path.join(ROOT, 'sdk.deploy.json');

// A target may pull the compiled output ("dist", the default — good for JS/non-TS
// consumers) or the raw TypeScript source ("src" — for TS consumers that compile
// the SDK with their own toolchain, e.g. the Companion module). The SDK source
// uses `.js` import specifiers so it drops cleanly into strict/verbatim setups.
function sourceDirFor(target) {
  return path.join(ROOT, target.from === 'src' ? 'src' : 'dist');
}

function copyDir(srcDir, destDir) {
  fs.mkdirSync(destDir, { recursive: true });
  for (const entry of fs.readdirSync(srcDir, { withFileTypes: true })) {
    const src = path.join(srcDir, entry.name);
    const dest = path.join(destDir, entry.name);
    if (entry.isDirectory()) {
      copyDir(src, dest);
    } else if (entry.isFile()) {
      fs.copyFileSync(src, dest);
    }
  }
}

// A guard header dropped into each target so it is obvious the folder is
// generated and must not be hand-edited.
function writeReadme(destDir) {
  const notice =
    '# Vendored ShowTrak Server SDK\n\n' +
    'This folder is generated by the ShowTrakServer-SDK-TS `deploy` script.\n' +
    'Do NOT edit these files here — change them in the SDK repo and redeploy.\n';
  fs.writeFileSync(path.join(destDir, 'README.md'), notice);
}

export function deploy() {
  const config = JSON.parse(fs.readFileSync(CONFIG, 'utf8'));
  const targets = Array.isArray(config.targets) ? config.targets : [];
  if (targets.length === 0) {
    console.warn('[sdk-deploy] No targets configured in sdk.deploy.json');
    return;
  }
  for (const target of targets) {
    if (!target || !target.to) continue;
    const srcDir = sourceDirFor(target);
    if (!fs.existsSync(srcDir)) {
      throw new Error(`Source ${srcDir} missing. Run "npm run build" first (or set from:"src").`);
    }
    const destDir = path.resolve(ROOT, target.to);
    fs.rmSync(destDir, { recursive: true, force: true });
    copyDir(srcDir, destDir);
    writeReadme(destDir);
    console.log(`[sdk-deploy] ${target.name || 'target'} (${target.from || 'dist'}) -> ${destDir}`);
  }
}

// Run when invoked directly (not when imported by watch.js).
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    deploy();
    console.log('[sdk-deploy] Done.');
  } catch (err) {
    console.error('[sdk-deploy] Failed:', err.message);
    process.exit(1);
  }
}
